name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/createclients:latest ./createClients
        docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/createproducts:latest ./createProducts
        docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/createsales:latest ./createSales

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Detectar el sistema operativo y usar el gestor de paquetes adecuado
          if command -v apt-get &> /dev/null
          then
            sudo apt-get update
            sudo apt-get install -y docker.io
          elif command -v yum &> /dev/null
          then
            sudo yum update -y
            sudo yum install -y docker
          else
            echo "No se pudo detectar el gestor de paquetes."
            exit 1
          fi

          # Iniciar y habilitar Docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Instalar Docker Compose
          if ! command -v docker-compose &> /dev/null
          then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Ejecutar los comandos Docker y Docker Compose
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/createclients:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/createproducts:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/createsales:latest
          sudo docker-compose up -d
